name:                happy-example
version:             0.1.0.0
github:              "kajigor/fl_2020_itmo_spr/"
license:             BSD3
author:              "Ekaterina Verbitskaia"
maintainer:          "kajigor@gmail.com"
copyright:           "Ekaterina Verbitskaia"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kajigor/fl_2020_itmo_spr/blob/HW10/#readme>

dependencies:
- base >= 4.7 && < 5
- array
- directory
- containers
- hedgehog
- HUnit
- tasty
- tasty-hedgehog
- tasty-hunit
- tasty-discover

library:
  source-dirs: src
  exposed-modules:
      PLex
      PParser
  other-modules : []

tests:
  test:
    main:                Test.hs
    source-dirs:         test
    dependencies:
    - happy-example
